%% open_pipeline_figure.m
%
% main script which creates the GUI for the batch process of dNEMO.
% 
% sets up the environment, runs several checks, preps several 
% structures which are separate to the main functions of the batch
% processing tool -- 
% 1) dNEMO
% 2) cellpose
% 3) u-track
% 
% note: it is recommended that, for a given image, to run it through the
% standalone dNEMO application first, in order to interact with the image
% and determine the proper settings for collecting data from images
% collected under the same experimental setup.
%

PIPELINE.MAIN = figure('units','normalized',...
                       'position',[0.075 0.15 0.85 0.675],...
                       'numbertitle','off',...
                       'menubar','none',...
                       'resize','on',...
                       'name','dNEMO batch processing');
%
PIPELINE.input_panel = uipanel('units','normalized',...
                               'position',[0.025 0.525 0.25 0.45],...
                               'title','Input Directory');
%
PIPELINE.input_textbox = uicontrol('style','edit',...
                                         'parent',PIPELINE.input_panel,...
                                         'units','normalized',...
                                         'position',[0.02 0.02 0.96 0.7],...
                                         'enable','off',...
                                         'visible','on');
%
PIPELINE.input_dir_display = uicontrol('style','edit',...
                                       'parent',PIPELINE.input_panel,...
                                       'units','normalized',...
                                       'position',[0.02 0.8 0.675 0.15],...
                                       'enable','inactive',...
                                       'visible','on');
%
PIPELINE.input_dir_select = uicontrol('style','push',...
                                      'parent',PIPELINE.input_panel,...
                                      'units','normalized',...
                                      'position',[0.725 0.8 0.235 0.15],...
                                      'enable','on',...
                                      'visible','on',...
                                      'String','Browse...');
%
PIPELINE.output_panel = uipanel('units','normalized',...
                                'position',[0.025 0.075 0.25 0.45],...
                                'title','Results Directory');
%
PIPELINE.output_textbox = uicontrol('style','edit',...
                                    'parent',PIPELINE.output_panel,...
                                    'units','normalized',...
                                    'position',[0.02 0.02 0.96 0.7],...
                                    'enable','off',...
                                    'visible','on');
%
PIPELINE.output_dir_display = uicontrol('style','edit',...
                                        'parent',PIPELINE.output_panel,...
                                        'units','normalized',...
                                        'position',[0.02 0.8 0.675 0.15],...
                                        'enable','inactive',...
                                        'visible','on');
%
PIPELINE.output_dir_select = uicontrol('style','push',...
                                       'parent',PIPELINE.output_panel,...
                                       'units','normalized',...
                                       'position',[0.725 0.8 0.235 0.15],...
                                       'enable','on',...
                                       'visible','on',...
                                       'String','Browse...');
%
PIPELINE.ignore_prev_results = uicontrol('style','checkbox',...
                                         'units','normalized',...
                                         'position',[0.025 0.025 0.25 0.05],...
                                         'enable','on',...
                                         'visible','off',...
                                         'String','Ignore images w/ previous results in directory.');
%
PIPELINE.settings_panel = uipanel('units','normalized',...
                                  'position',[0.3 0.025 0.35 0.95],...
                                  'title','Operation Settings');
%
PIPELINE.settings_textbox = uicontrol('style','edit',...
                                      'parent',PIPELINE.settings_panel,...
                                      'units','normalized',...
                                      'position',[0.02 0.32 0.96 0.505],...
                                      'enable','off',...
                                      'visible','on',...
                                      'fontsize',16,...
                                      'horizontalalignment','left');
%
PIPELINE.settings_file_display = uicontrol('style','edit',...
                                           'parent',PIPELINE.settings_panel,...
                                           'units','normalized',...
                                           'position',[0.02 0.875 0.675 0.075],...
                                           'enable','off',...
                                           'visible','on');
%
PIPELINE.settings_file_select = uicontrol('style','push',...
                                          'parent',PIPELINE.settings_panel,...
                                          'units','normalized',...
                                          'position',[0.725 0.875 0.25 0.075],...
                                          'enable','on',...
                                          'visible','on',...
                                          'String','Browse...');
%
PIPELINE.dnemo_checkbox = uicontrol('style','checkbox',...
                                    'parent',PIPELINE.settings_panel,...
                                    'units','normalized',...
                                    'position',[0.02 0.25 0.35 0.05],...
                                    'enable','on',...
                                    'visible','on',...
                                    'String','Run dNEMO',...
                                    'fontsize',14,...
                                    'value',1);
%
PIPELINE.cellpose_checkbox = uicontrol('style','checkbox',...
                                       'parent',PIPELINE.settings_panel,...
                                       'units','normalized',...
                                       'position',[0.02 0.18 0.32 0.05],...
                                       'enable','on',...
                                       'visible','on',...
                                       'String','Run Cellpose',...
                                       'fontsize',14,...
                                       'value',1);
%
PIPELINE.cellpose_use_ref_images = uicontrol('style','checkbox',...
                                             'parent',PIPELINE.settings_panel,...
                                             'units','normalized',...
                                             'position',[0.375 0.18 0.55 0.05],...
                                             'enable','on',...
                                             'visible','off',...
                                             'String','Use REF image files (where available)',...
                                             'fontsize',12,...
                                             'value',0);
%
PIPELINE.utrack_checkbox = uicontrol('style','checkbox',...
                                     'parent',PIPELINE.settings_panel,...
                                     'units','normalized',...
                                     'position',[0.02 0.11 0.35 0.05],...
                                     'enable','on',...
                                     'visible','off',...
                                     'String','Run u-track',...
                                     'fontsize',14,...
                                     'value',0);
%
PIPELINE.log_window = uicontrol('style','edit',...
                                'units','normalized',...
                                'position',[0.675 0.42 0.3 0.55],...
                                'fontsize',14,...
                                'horizontalalignment','left',...
                                'enable','inactive',...
                                'visible','on');
%
PIPELINE.confirm_button = uicontrol('style','push',...
                                    'units','normalized',...
                                    'position',[0.675 0.275 0.3 0.125],...
                                    'enable','on',...
                                    'visible','on',...
                                    'String','CONFIRM VALID INPUT ARGUMENTS',...
                                    'fontsize',14);
%
PIPELINE.start_button = uicontrol('style','push',...
                                  'units','normalized',...
                                  'position',[0.675 0.135 0.3 0.125],...
                                  'enable','off',...
                                  'visible','on',...
                                  'String','START',...
                                  'fontsize',14);
%
%% accepted image formats (DV, TIFF)
%

valid_image_format_arg = {'*.dv;*.DV;*.tif;*.TIF;*.tiff;*.TIFF'};
setappdata(PIPELINE.MAIN,'valid_image_format_arg',valid_image_format_arg);

%% global variable assigment
%

dnemo_param_struct = struct;
setappdata(PIPELINE.MAIN,'dnemo_param_struct',dnemo_param_struct);

cellpose_param_struct = struct;
setappdata(PIPELINE.MAIN,'cellpose_param_struct',cellpose_param_struct);

utrack_param_struct = struct;
setappdata(PIPELINE.MAIN,'utrack_param_struct',utrack_param_struct);

pipeline_operations = struct;
pipeline_operations.RUN_DNEMO = PIPELINE.dnemo_checkbox.Value;
pipeline_operations.RUN_CELLPOSE = PIPELINE.cellpose_checkbox.Value;
pipeline_operations.RUN_UTRACK = PIPELINE.utrack_checkbox.Value;
setappdata(PIPELINE.MAIN,'pipeline_operations',pipeline_operations);

%
%% callback assignment
%

set(PIPELINE.input_dir_select,'callback',{@input_directory_select, PIPELINE});
set(PIPELINE.output_dir_select,'callback',{@output_directory_select, PIPELINE});
set([PIPELINE.dnemo_checkbox, PIPELINE.cellpose_checkbox, PIPELINE.utrack_checkbox],'callback',{@operation_update, PIPELINE});
set(PIPELINE.confirm_button,'callback',{@confirm_input_arguments, PIPELINE});
set(PIPELINE.start_button,'callback',{@run_pipeline, PIPELINE});

%% application setup
%

% default parameter initialization
default_param_filename = 'default_pipeline_param_SP.txt';
default_param_filepath = cd;

parse_pipeline_parameters(PIPELINE, default_param_filename, default_param_filepath);

%
%%%
%%%%%
%%%
%